### ISSUE TITLE
`npm run test` failed 

### ISSUE THREAD

**Issue by gary02** [thematters/matters-html-formatter#102]
**Describe the bug**
two tests throw `Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error`

**To Reproduce**
1. git clone  this repo
2. cd to root dir and run `npm ci` or `npm i`
3. run `npm run test`

**Expected behavior**
test pass without errors

**Screenshots**
`npm run test` :
![2022-08-16-113232_2096x941_scrot](https://user-images.githubusercontent.com/13580441/184792426-43657756-847e-4a96-b5ff-4e524aeec70d.png)

**Desktop (please complete the following information):**
 - node: v16.16.0
 - npm: 8.11.0
 - git  revision: 9242e4c4196973d0c5d472ab6bc9767afb8966e2

**Additional context**

I tried upgrading jest family to v28, but tests still failed with same errors after work out other problems brought by upgrade

**Comment by gary02** [comment]
setTimeout to big number can be a workaround. But the tests still failed and take too much time:

![2022-08-16-131217_1867x826_scrot](https://user-images.githubusercontent.com/13580441/184802643-e0d0a545-44fb-4a4b-9490-bafc237cbe45.png)

**Comment by gary02** [comment]
https://github.com/thematters/matters-html-formatter/blob/9242e4c4196973d0c5d472ab6bc9767afb8966e2/src/makeHtmlBundle/getAsset.ts#L35-L47

the two test errors above are caused by `fetch` function.

I think `fetch` should be mocked and tests the cases  that  `fetch` throw errors or not

**Comment by guoliu** [comment]
> https://github.com/thematters/matters-html-formatter/blob/9242e4c4196973d0c5d472ab6bc9767afb8966e2/src/makeHtmlBundle/getAsset.ts#L35-L47
> 
> The 2 test errors above are caused by `fetch` function which fail to fetch files and throw error in my env.
> 
> I think `fetch` should be mocked and tests the cases that `fetch` throws errors or not

Great catch! Yes `fetch` should definitely be mocked to be independent of the local network.
