### ISSUE TITLE
[Formatter] extend matters-html-formatter to be able to bundle any arbitrary multiple files content

### ISSUE THREAD

**Issue by tx0c** [thematters/matters-html-formatter#104]
https://www.notion.so/matterslab/Publish-content-feed-to-IPNS-from-Matters-server-e294ee05fc76479c893dd6c24370caaf

> [discussion] can be modified from ‣(renamed as matters-content-store?)

**Comment by Jasmine-liang** [comment]
Could also consider this request from [Matters文章现在可以一键在线转为墙内链接了](https://matters.news/@deserve/7484-matters%E6%96%87%E7%AB%A0%E7%8E%B0%E5%9C%A8%E5%8F%AF%E4%BB%A5%E4%B8%80%E9%94%AE%E5%9C%A8%E7%BA%BF%E8%BD%AC%E4%B8%BA%E5%A2%99%E5%86%85%E9%93%BE%E6%8E%A5%E4%BA%86-zdpuB1bvMnsAr4APk12FmdRxcqMaEsRo46vKE7p6Arvsg4YiF)

> 最后说两句，分享Matters的IPFS地址文章有个问题，就是IPFS地址的内容只有文章原文，没有评论内容，甚至连原文链接都没有（这里我想建议Matters在生成IPFS内容的时候，专门加一个原文地址链接在里面，这样即使别人看到的是IPFS内容，也可以链接回Matters参与讨论）。Matters的评论区质量这么高，但是分享出去IPFS地址的文章，别人却找不到原文入口，也就不利于促成更多的讨论了。

**Comment by Jasmine-liang** [comment]
[UTC+8, 2022.09.07]
Discussed after Dev Sync meeting: No need of adding original article link(from Matters) into IPFS article. Since there's no need of emphasizing Matters during the process of decentralization🫡

**Comment by devformatters** [comment]
> [UTC+8, 2022.09.07] Discussed after Dev Sync meeting: No need of adding original article link(from Matters) into IPFS article. Since there's no need of emphasizing Matters during the process of decentralization🫡

And we'll have more discussion around this in the future. Before that, let's just make IPNS Feed work.

**Comment by devformatters** [comment]
@Jasmine-liang I'll close it, since Tomas and you have implemented in other PR.
